### ISSUE TITLE
EnableLiveUpdate on UWP

### ISSUE THREAD

**Issue by MaxWilson** [fsprojects/Fabulous#167]
**Repro:**

Check out https://github.com/nosami/Elmish.Calculator and add a UWP app to it. (VS: right click on solution, Add Project | C# | Cross-platform | Xamarin.Forms, blank app.) In the UWP app, add a reference to Elmish.Calculator and set EntryPoint in package.appxmanifest to Elmish.Calculator.App, and set MainPage.xaml.cs to LoadApplication(new Elmish.Calculator.App()).

Run or debug the UWP app.

**Expected:** shows calculator app, runs fine
**Actual:** shows calculator app for about ten seconds, then throws a SocketException and terminates.

```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=Only one usage of each socket address (protocol/network address/port) is normally permitted
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(Int32 port, AddressFamily family)
   at <StartupCode$Elmish-XamarinForms-LiveUpdate>.$LiveUpdate.Start@45-2.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$Elmish-XamarinForms-LiveUpdate>.$LiveUpdate.Start@71-14.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@938-1.Invoke(ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Async.Sleep@1355-1.Invoke(Object _arg3)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__19_0(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Additional info:**

Commenting out **do runner.EnableLiveUpdate ()** makes the SocketException go away.

**System details:**

Windows 10, Visual Studio 15.8.1.

**Comment by dsyme** [comment]
Labelling as an ehancement.

UWP+LiveUpdate hasn't been tested at all beyond the above, so is currently out of scope - if you'd like to add it that would be great. We'd need CI testing for a basic UWP app.

**Comment by MaxWilson** [comment]
I'd love to, but I'm not sure where to even begin. Is there anywhere I could go to learn about how EnableLiveUpdate works from an architectural standpoint?

**Comment by dsyme** [comment]
I added some brief design notes on how live update works here: https://fsprojects.github.io/Elmish.XamarinForms/tools.html#design

Miguel pointed out that on Android we can likely just send DLLs over the wire and Assembly.Load them

**Comment by MaxWilson** [comment]
The link https://fsprojects.github.io/Elmish.XamarinForms/tools.html#design does not work for me.

**Comment by dsyme** [comment]
@MaxWilson It means this https://github.com/fsprojects/Fabulous/blob/master/fscd/CodeModel.fs

Everything in those notes refers to stuff under https://github.com/fsprojects/Fabulous/blob/master/fscd/

**Comment by xperiandri** [comment]
Does it work?

```
fscd: ERROR SENDING TO WEBHOOK: "System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at System.Net.WebClient.UploadString(String address, String method, String data)
   at FSharp.Compiler.PortaCode.ProcessCommandLine.sendToWebHook@218.Invoke(String hook, FSharpList`1 fileContents) in D:\a\1\s\paket-files\neutral\fsprojects\FSharp.Compiler.PortaCode\src\ProcessCommandLine.fs:line 223"
```

**Comment by TimLariviere** [comment]
LiveUpdate has been abandoned in v2. Might come back in the future
