### ISSUE TITLE
Build fails when using Release config

### ISSUE THREAD

**Issue by sandeepc24** [fsprojects/Fabulous#331]
Build fails when building app using Release config with following error

```
Severity    Code    Description    Project    File    Line    Suppression State
Error        MSB4018: The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Fabulous.DynamicViews.ViewElement Slider::slider(Microsoft.FSharp.Collections.FSharpList`1<Slider/ISliderProp>)' in assembly: 'Fabulous.SimpleElements.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Fabulous.DynamicViews.AttributeKey`1<System.Double> Fabulous.DynamicViews.View::get__MinimumAttribKey()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()             0  
```

**Comment by TimLariviere** [comment]
@sandeepc24 Which version of Fabulous do you use?

In Fabulous v0.29, `Slider.Minimum`/`Slider.Maximum` was replaced by `Slider.MinimumMaximum`.
>Mono.Cecil.ResolutionException: Failed to resolve Fabulous.DynamicViews.AttributeKey`1<System.Double> Fabulous.DynamicViews.View::get__MinimumAttribKey()

This seems to be an issue related to fabulous-simple-elements, which is built against Fabulous v0.22.
So there's a chance it's not compatible anymore. (especially when Fabulous v0.32 will be out)
>(...) in assembly: 'Fabulous.SimpleElements.dll'

**Comment by dsyme** [comment]
@TimLariviere I think we should move to semantic versioning, where we simply bump the major version on every release unless we're sure that things are binary-compatible. I know this means versions like `53.0.0.1` but I think that's ok, no one minds in practice.

**Comment by TimLariviere** [comment]
@dsyme Ok. That's a good idea. Though I'd like to start using this only when we hit a stable v1.0 (https://github.com/fsprojects/Fabulous/milestone/1).

For the moment, I bump the minor version whenever there's a new API or a breaking change. The patch version is bumped only when it's only bug fixes.

**Comment by TimLariviere** [comment]
@sandeepc24 Has your issue been solved?

**Comment by sandeepc24** [comment]
Yes, this is fixed. I will close this issue.
