### ISSUE TITLE
building default sample app fails if Android SDK 9.0 not installed

### ISSUE THREAD

**Issue by CMThre3** [fsprojects/Fabulous#471]
steps to reproduce

1. install templates using getting started guide to create new app
2. target personal android device (android 8.1)
3. build

expected to build, actual is build failure, first error line: 
```
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1765,2): error APT0000: max res 27, skipping values-v28 "max res 27, skipping values-v28".
```
because this seems to be due to API verion number, we changed the API version number in android manifest.xml which changed the errors to warnings but something still seems wrong.

log:
```
1>------ Rebuild All started: Project: SqueakyApp, Configuration: Debug Any CPU ------
1>SqueakyApp -> H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp\bin\Debug\netstandard2.0\SqueakyApp.dll
2>------ Rebuild All started: Project: SqueakyApp.Android, Configuration: Debug Any CPU ------
2>		"H:\Documents\F# Xamarin Forms\SqueakyApp\.nuget\NuGet.exe" install "H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\packages.config" -source "https://www.nuget.org/api/v2/"  -NonInteractive -RequireConsent -solutionDir "H:\Documents\F# Xamarin Forms\SqueakyApp"
2>		Restoring NuGet packages...
2>		To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the NuGet Package Manager node and uncheck 'Allow NuGet to download missing packages'.
2>		Feeds used:
2>		  C:\Users\Admin\.nuget\packages\
2>		  https://www.nuget.org/api/v2/
2>		All packages listed in H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\packages.config are already installed.
2>		No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1765,2): error APT0000: max res 27, skipping values-v28 "max res 27, skipping values-v28".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1765,2): error APT0000: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1765,2): error APT0000: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Core.Common (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Core.Runtime (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Lifecycle.Common (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Lifecycle.LiveData.Core (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Lifecycle.Runtime (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Arch.Lifecycle.ViewModel (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Animated.Vector.Drawable (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Annotations (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.AsyncLayoutInflater (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Collections (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Compat (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.CoordinaterLayout (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.UI (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.Utils (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.CursorAdapter (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.CustomTabs (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.CustomView (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Design (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.DocumentFile (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.DrawerLayout (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Fragment (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Interpolator (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Loader (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.LocalBroadcastManager (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Media.Compat (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Print (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.SlidingPaneLayout (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.SwipeRefreshLayout (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Transition (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v4 (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.AppCompat (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.CardView (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.MediaRouter (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.Palette (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.RecyclerView (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Vector.Drawable (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.VersionedParcelable (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.ViewPager (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.Android (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>H:\Documents\F# Xamarin Forms\SqueakyApp\SqueakyApp.Android\SqueakyApp.Android.fsproj: warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>		No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
2>System.IO.FileNotFoundException: Could not load assembly 'SqueakyApp.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
2>File name: 'SqueakyApp.Android.dll'
2>   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
2>   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
2>   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "SqueakyApp.Android.fsproj" -- FAILED.
2>
2>Build FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

visual studio version info:
```
Microsoft Visual Studio Community 2019
Version 16.1.3
VisualStudio.16.Release/16.1.3+29009.5
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.543 (d16-1@34a619991)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.22 (HEAD/8e7764fdf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3cb36842fc4
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.153 (750a879)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by CMThre3** [comment]
modifying line 13 from 
```
<TargetFrameworkVersion>v8.1</TargetFrameworkVersion>
```
to 
```
<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>
```
seems to allow the build to complete without any error

**Comment by TimLariviere** [comment]
@CMThre3 That's weird.
The TargetFrameworkVersion is correctly set to `v9.0` in the templates.
Just uninstalled Fabulous.Templates and reinstalled it, then ran the command to create a new app on macOS and it worked as expected (`<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>`, no warnings).

Could you try again to create an app with the command `dotnet new fabulous-app -n SomeName` and check the `TargetFrameworkVersion` before opening the solution with Visual Studio?

I have the feeling Visual Studio switched the TargetFrameworkVersion back to v8.1 (missing Android SDK v28?)

**Comment by dsyme** [comment]
We installed Android SDK v28 in between (was not there by default AFAIK), so we should check with/without that.

Shame the error message was so baroque!

**Comment by mallibone** [comment]
Hmm, I believe I know what causes the issue when going targeting `v8.1` - the Android SDK v28 supports multiple Android versions. We currently reference the target of Version 9.0 in the csproj of Android. I believe this is needed by msbuild. The new PackageReference NuGet packages eliminate the need of defining the NuGet targets file - but I'll have to do some digging to understand what is exactly happening here.

**Comment by CMThre3** [comment]
I've confirmed that this behavior only occurs when the android v9.0 SDK is not installed when the application is built and launched, the TargetFrameworkVersion is automatically changed to v8.1 which causes a build failure, I'll submit a separate PR to instruct the user to install the v9.0 SDK in the Getting Started document.

**Comment by CMThre3** [comment]
@mallibone just saw your comment as I posted, I'll prepare a PR to change the docs, please accept if you see fit.

**Comment by TimLariviere** [comment]
@CMThre3 @dsyme Are you working on this issue?

**Comment by dsyme** [comment]
@TimLariviere No, we just updated the getting-started docs instead

**Comment by dsyme** [comment]
I think we can close this - I haven't noticed this particular problem as I walked through things now

**Comment by dsyme** [comment]
I think we can close this - I haven't noticed this particular problem as I walked through things now
