### ISSUE TITLE
Error sending to webhook macOS + Rider / Visual Studio

### ISSUE THREAD

**Issue by Falconerd** [fsprojects/Fabulous#578]
Hey y'all, I got this error. I tried running with elevated permissions by using these commands: 
`sudo fabulous --watch --send` and `sudo /path-to/rider` or `sudo /path-to/visual-studio`.

```
fscd: CHANGE DETECTED (Renamed), COMPILING....
fscd: COMPILED /Users/falconerd/dev/SqueakyApp/SqueakyApp/obj/Debug/netstandard2.0/SqueakyApp.AssemblyInfo.fs
fscd: GOT PortaCode for /Users/falconerd/dev/SqueakyApp/SqueakyApp/obj/Debug/netstandard2.0/SqueakyApp.AssemblyInfo.fs
fscd: COMPILED /Users/falconerd/dev/SqueakyApp/SqueakyApp/SqueakyApp.fs
fscd: GOT PortaCode for /Users/falconerd/dev/SqueakyApp/SqueakyApp/SqueakyApp.fs
fscd: GOT JSON, length = 653718
fscd: SENDING TO WEBHOOK... 
fscd: ERROR SENDING TO WEBHOOK: "System.Net.WebException: Connection refused Connection refused ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at FSharp.Compiler.PortaCode.ProcessCommandLine.sendToWebHook@218.Invoke(String hook, FSharpList`1 fileContents) in D:\a\1\s\paket-files\neutral\fsprojects\FSharp.Compiler.PortaCode\src\ProcessCommandLine.fs:line 222"```

**Comment by Falconerd** [comment]
I managed to get live reloading working by removing the project, rerunning `dotnet new fabulous-xf-app -n SqueakyApp --macOS` and not use `sudo` at all.

So I'm not sure what the issue was or how to fix it without restarting a project.
