### ISSUE TITLE
Linker error with XF 4.6.0.772

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#739]
> Xamarin.Android.Common.targets(1942, 5): [XALNK7000] Mono.Linker.MarkException: Error processing method: 'System.Void Fabulous.XamarinForms.ViewBuilders::UpdateExpander(Microsoft.FSharp.Core.FSharpValueOption`1<Fabulous.ViewElement>,Fabulous.ViewElement,Xamarin.Forms.Expander)' in assembly: 'Fabulous.XamarinForms.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.BindableProperty Xamarin.Forms.Expander::SpacingProperty
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()

Having latest Fabulous, i got an error above trying to link on Android. Looks suspicious.

**Comment by TimLariviere** [comment]
Seems like a breaking change has been introduced in this version:
https://github.com/xamarin/Xamarin.Forms/commit/b11153d7197a613f44d392c271b60b17e9b58356

Will release a fix for that.
